"""added operations table

Revision ID: 5a4126a2caf0
Revises: ca79886a6aeb
Create Date: 2021-09-24 16:59:37.620345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4126a2caf0'
down_revision = 'ca79886a6aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
