"""unique operation_no

Revision ID: 852dfd766c9d
Revises: 65210b3f37bf
Create Date: 2021-09-30 21:38:30.080343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852dfd766c9d'
down_revision = '65210b3f37bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operations_operation_no_key', 'operations', type_='unique')
    op.create_index(op.f('ix_operations_operation_no'), 'operations', ['operation_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_operation_no'), table_name='operations')
    op.create_unique_constraint('operations_operation_no_key', 'operations', ['operation_no'])
    # ### end Alembic commands ###
