"""migrate for test db

Revision ID: 8cdd23676e05
Revises: f9cf423e3280
Create Date: 2021-09-30 20:26:41.457876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdd23676e05'
down_revision = 'f9cf423e3280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
