"""added operations table

Revision ID: dbb74ef6fe6d
Revises: 219cb5d89fb0
Create Date: 2021-09-30 18:58:48.569093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb74ef6fe6d'
down_revision = '219cb5d89fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
