"""removed audit

Revision ID: f9cf423e3280
Revises: dbb74ef6fe6d
Create Date: 2021-09-30 18:59:37.743042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cf423e3280'
down_revision = 'dbb74ef6fe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
